universe                = vanilla
executable              = one_wrap.sh
arguments               = $(MIX)
transfer_input_files    = mm_one_mixture.py
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = drift_9010_$(MIX).json
output                  = logs/$(MIX).out
error                   = logs/$(MIX).err
log                     = logs/array.clog
request_cpus            = 1
request_memory          = 2 GB
+MaxRuntime             = 5400
queue MIX from mixtures.txt
