executable = condor_mb.sh
arguments = $(tag)
transfer_input_files = magboltz_drift.py, setup_garfield.sh, /afs/cern.ch/user/d/dneff/work/garfield_install/garfield-927e5c21.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = log/mbatt_$(tag).out
error = log/mbatt_$(tag).err
log = log/mb.log
+JobFlavour = "workday"
queue tag in (beam_w1p7 beam_w1p7_o0p05 beam_w1p7_o0p1 beam_w1p7_o0p2 bench_w0p5 bench_w0p5_o0p05)
