executable = condor_mb.sh
arguments = $(tag)
transfer_input_files = magboltz_drift.py, setup_garfield.sh, /afs/cern.ch/user/d/dneff/work/garfield_install/garfield-927e5c21.tar.gz
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = log/mb_$(tag).out
error = log/mb_$(tag).err
log = log/mb.log
+JobFlavour = "workday"
queue tag in (bench_dry bench_w0p25 bench_w0p5 bench_w1 bench_w2 beam_dry beam_w0p5 beam_w1p7 beam_w3)
