#!/usr/bin/env python3
"""T4: are the extra liquid hits that `STEP SIZE` 1/3 buys REAL pulses?

The v11 -> v12 change is the whole liquid yield claim (+14-21 %). A finer
derivative window resolves pileup, but it can equally double-fire on noise or
split one pulse into two, and chi2-neutrality plus a rising pileup flag are
consistent with either. This matches the two processings hit-by-hit and
characterises the hits that only v12 has.

Matching is by (tree, bunch, time) with a tolerance: the SAME pulse is
reconstructed at very nearly the same time by both, so anything in v12 without a
v11 partner within `TOL` ns is new. Matching is greedy nearest-neighbour on
sorted times, which is exact here because the tolerance is far below the median
hit spacing (24-30 ns).

Three proxies, none of which needs raw waveforms:

  (i)   AMPLITUDE. A fake population produced by noise double-firing is pinned
        just above threshold. If the new hits have an amplitude distribution
        resembling the pre-existing ones, they are not threshold noise.
  (ii)  TIME OF FLIGHT. Real hits follow the beam's rate profile, which falls
        steeply with time of flight. Fakes generated by the pulse finder are
        flat in time, or track the local hit density rather than the physics.
  (iii) SPLIT vs RECOVERY. What fraction of new hits sit within 150 ns of a
        pre-existing hit (a resolved shoulder on an existing pulse) versus in
        the open (a pulse the coarser step size missed entirely). Both are real;
        the point is to know the mix, because a split population that is ALSO
        pinned at low amplitude is the fake-hit signature.

    python new_hits.py <v11.root> <v12.root> [TREE ...]
"""
import sys

import numpy as np
import uproot

TREES = ('LIQA', 'LIQB', 'LIQC', 'LIQD')
TOL = 3.0                  # ns; same pulse, both processings
NEAR = 150.0               # ns; the slow-component tail of an existing pulse
T_LO, T_HI = 1_000_000.0, 18_000_000.0
BR = ['BunchNumber', 'tof', 'tflash', 'amp', 'chi2']


def load(path, tree):
    a = uproot.open(path)[tree].arrays(BR, library='np')
    t = a['tof'] - a['tflash']
    m = (t > T_LO) & (t < T_HI)
    b, t, amp, chi2 = a['BunchNumber'][m], t[m], np.abs(a['amp'][m]), a['chi2'][m]
    o = np.lexsort((t, b))
    return b[o], t[o], amp[o], chi2[o]


def new_mask(b_old, t_old, b_new, t_new):
    """True where a (bunch, time) in the NEW set has no OLD partner within TOL."""
    out = np.ones(len(b_new), bool)
    # both are already sorted by (bunch, time); walk bunch by bunch
    ub = np.unique(b_new)
    s_o = np.searchsorted(b_old, ub)
    e_o = np.searchsorted(b_old, ub, side='right')
    s_n = np.searchsorted(b_new, ub)
    e_n = np.searchsorted(b_new, ub, side='right')
    for k in range(len(ub)):
        to = t_old[s_o[k]:e_o[k]]
        tn = t_new[s_n[k]:e_n[k]]
        if to.size == 0 or tn.size == 0:
            continue
        j = np.clip(np.searchsorted(to, tn), 0, to.size - 1)
        j0 = np.clip(j - 1, 0, to.size - 1)
        d = np.minimum(np.abs(tn - to[j]), np.abs(tn - to[j0]))
        out[s_n[k]:e_n[k]] = d > TOL
    return out


def gap_to_old(b_old, t_old, b_new, t_new):
    """Distance from each NEW hit to the nearest pre-existing hit, same bunch."""
    out = np.full(len(b_new), np.inf)
    ub = np.unique(b_new)
    s_o, e_o = np.searchsorted(b_old, ub), np.searchsorted(b_old, ub, side='right')
    s_n, e_n = np.searchsorted(b_new, ub), np.searchsorted(b_new, ub, side='right')
    for k in range(len(ub)):
        to, tn = t_old[s_o[k]:e_o[k]], t_new[s_n[k]:e_n[k]]
        if to.size == 0 or tn.size == 0:
            continue
        j = np.clip(np.searchsorted(to, tn), 0, to.size - 1)
        j0 = np.clip(j - 1, 0, to.size - 1)
        out[s_n[k]:e_n[k]] = np.minimum(np.abs(tn - to[j]), np.abs(tn - to[j0]))
    return out


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 1
    old_p, new_p = sys.argv[1], sys.argv[2]
    trees = sys.argv[3:] or TREES
    for tree in trees:
        b_o, t_o, a_o, c_o = load(old_p, tree)
        b_n, t_n, a_n, c_n = load(new_p, tree)
        nm = new_mask(b_o, t_o, b_n, t_n)
        print(f'\n=== {tree} ===')
        print(f'  v11 {len(b_o):9,d} hits   v12 {len(b_n):9,d} hits '
              f'({len(b_n) / len(b_o) - 1:+.1%})')
        print(f'  matched {(~nm).sum():9,d}   v12-only (NEW) {nm.sum():9,d} '
              f'({nm.mean():.1%} of v12)')
        lost = new_mask(b_n, t_n, b_o, t_o)
        print(f'  v11-only (LOST) {lost.sum():9,d} ({lost.mean():.1%} of v11)')

        # (i) amplitude
        qs = [10, 25, 50, 75, 90]
        po = np.percentile(a_o, qs)
        pn = np.percentile(a_n[nm], qs)
        print('  (i)  amplitude percentiles      ' +
              '  '.join(f'p{q}' for q in qs))
        print(f'       pre-existing (v11)        ' +
              '  '.join(f'{v:6.0f}' for v in po))
        print(f'       NEW hits                  ' +
              '  '.join(f'{v:6.0f}' for v in pn))
        print(f'       new-hit median / pre-existing median = '
              f'{pn[2] / po[2]:.2f}')
        # The AREA/AMP elimination cut sits at amp 50. A population created by
        # the finder re-firing on noise piles up against that edge; a population
        # of genuine small pulses does not know the cut is there.
        for edge in (60.0, 80.0):
            print(f'       within {edge - 50:.0f} ADC of the amp-50 cut: '
                  f'pre-existing {np.mean(a_o < edge):.1%}, '
                  f'NEW {np.mean(a_n[nm] < edge):.1%}')

        # (ii) time-of-flight profile, in decades
        print('  (ii) time-of-flight profile (fraction of each population)')
        print(f'       {"tof [ms]":>14s} {"pre-existing":>13s} {"NEW":>8s} '
              f'{"ratio":>7s}')
        for lo, hi in ((1, 3), (3, 10), (10, 20), (20, 40), (40, 80),
                       (80, 200), (200, 18000)):
            mo = (t_o >= lo * 1e6) & (t_o < hi * 1e6)     # bin edges in ms
            mn = (t_n[nm] >= lo * 1e6) & (t_n[nm] < hi * 1e6)
            if mo.sum() < 50:
                continue
            fo, fn = mo.mean(), mn.mean()
            print(f'       {lo:6d}-{hi:<7d} {fo:12.3%} {fn:8.3%} '
                  f'{fn / fo if fo else float("nan"):7.2f}')

        # (iii) split vs recovery
        g = gap_to_old(b_o, t_o, b_n[nm], t_n[nm])
        split = g < NEAR
        print(f'  (iii) {split.mean():.1%} of new hits are within {NEAR:.0f} ns '
              f'of a pre-existing hit (SPLIT / shoulder)')
        print(f'        {1 - split.mean():.1%} sit in the open (RECOVERY)')
        for lab, m in (('        split   ', split), ('        recovery', ~split)):
            if m.sum() > 100:
                print(f'{lab} n={m.sum():8,d}  amp p50 {np.median(a_n[nm][m]):6.0f}  '
                      f'chi2 p50 {np.median(c_n[nm][m]):6.2f}')
        # the tightest new hits are the ones most likely to be a re-fire on the
        # same pulse: quote how many land inside one pulse width
        print(f'        of the split ones, {np.mean(g[split] < 10):.1%} are '
              f'within 10 ns (< 2 pulse FWHM) of the pre-existing hit')
    return 0


if __name__ == '__main__':
    sys.exit(main())
