#!/usr/bin/env python3
"""Self-contained checks of the two sharing-kernel forms.

The original regression test (test_model_regression.py) needs the R&D
artefacts that were lost with the campaign machine, so it can no longer run.
This test needs nothing on disk: it builds a synthetic bundle and checks the
properties the ``share_lp`` port (2026-08-05) must preserve:

  1. delay mode is unchanged in behaviour (copy peaks tau_s late, area c1),
  2. lp mode's copy peaks near the central strip and carries a longer tail,
  3. lp mode conserves the copy's area (RC is area-preserving) within the
     window,
  4. chi2_plane round-trips: waveforms generated by the model are fitted
     back to the generating (p0, w) by fit_plane_raw in both modes.

    ../../.venv/bin/python wft/tests/test_share_modes.py
"""
import os
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from wft.calib import CalibrationBundle              # noqa: E402
from wft import model as wm                          # noqa: E402


def synth_bundle():
    grid = np.arange(-360.0, 1400.0, 10.0)
    # a plausible shaped pulse: gamma-ish rise, exponential fall, undershoot
    t = np.clip(grid, 0, None)
    tmpl = (t / 180.0) ** 2 * np.exp(-t / 180.0)
    tmpl -= 0.06 * (t / 800.0) * np.exp(-t / 800.0)
    tmpl /= tmpl.max()
    tmpl[grid < 0] = 0.0
    return CalibrationBundle(
        hyper=dict(c1=0.25, c2=0.10, kY=1.0, tau_s=60.0, sigma_s=50.0,
                   sigma_p0=0.10, Dp=0.02),
        v_drift=34.0, grid=grid,
        tmpl={'x': tmpl, 'y': tmpl},
        gain={'x': np.ones(512), 'y': np.ones(512)},
        detector='synthetic', run_key='test')


def copy_props(mode, tau):
    wm.set_share_mode(mode)
    h = dict(wm.HYPER)
    h['tau_s'] = tau
    # isolate the resistive kernel: no geometric spill onto the neighbour
    h['sigma_p0'] = 0.01
    h['Dp'] = 0.001
    pos = (np.arange(5) - 2) * wm.PITCH
    M = wm.build_matrix('x', pos, 0.0, 0.0, 200.0, h)
    q = np.zeros(wm.K)
    q[3] = 1.0                                     # single depth bin
    W = (M @ q).reshape(5, wm.NSAMP)
    c, n1 = W[2], W[1]
    ts = np.arange(wm.NSAMP) * 60.0
    return dict(pk_shift=ts[n1.argmax()] - ts[c.argmax()],
                area_ratio=n1.sum() / c.sum(),
                pk_ratio=n1.max() / c.max())


def main():
    cal = synth_bundle()
    wm.use_calibration(cal)
    wm.set_nsamp(32)
    ok = True

    d = copy_props('delay', 300.0)
    print(f"delay tau=300: shift {d['pk_shift']:+.0f} ns  "
          f"area {d['area_ratio']:.3f}  peak {d['pk_ratio']:.3f}")
    assert 240 <= d['pk_shift'] <= 360, "delay copy must peak ~tau_s late"
    assert abs(d['area_ratio'] - 0.25) < 0.03, "delay copy area must be ~c1"

    l = copy_props('lp', 300.0)
    print(f"lp    tau=300: shift {l['pk_shift']:+.0f} ns  "
          f"area {l['area_ratio']:.3f}  peak {l['pk_ratio']:.3f}")
    assert 60 <= l['pk_shift'] <= 300, \
        "lp copy must peak between the central peak and +tau"
    assert l['pk_shift'] < d['pk_shift'], "lp copy peaks earlier than delayed"
    assert l['pk_ratio'] < d['pk_ratio'], "lp copy is dispersed (lower peak)"
    assert abs(l['area_ratio'] - 0.25) < 0.04, \
        "lp copy area must stay ~c1 (RC preserves area)"

    # small-tau continuity: lp(tau->60) ~ delay(tau=60)
    d60, l60 = copy_props('delay', 60.0), copy_props('lp', 60.0)
    assert abs(d60['area_ratio'] - l60['area_ratio']) < 0.02
    assert abs(d60['pk_ratio'] - l60['pk_ratio']) < 0.10

    # round-trip fit in both modes
    rng = np.random.default_rng(1)
    for mode in ('delay', 'lp'):
        wm.set_share_mode(mode)
        h = dict(wm.HYPER)
        pos = (np.arange(9) - 4) * wm.PITCH
        p0_true, w_true, t0_true = 0.31, 2.0e-3, 240.0
        M = wm.build_matrix('x', pos, p0_true, w_true, t0_true, h)
        q = np.exp(-0.5 * ((np.arange(wm.K) - 8) / 4.0) ** 2)
        W = (M @ q).reshape(9, wm.NSAMP) * 800.0
        W += rng.normal(0, 4.0, W.shape)
        P = dict(W=W, pos=pos, noise=np.full(9, 4.0), ch=np.arange(9))
        r = wm.fit_plane_raw(P, 'x', 0.0, 0.0, 200.0, hyper=h)
        dp, dw = abs(r['p0'] - p0_true), abs(r['w'] - w_true)
        print(f"{mode:5s} round-trip: dp0 {dp * 1e3:.1f} um  "
              f"dw {dw * 1e3:.3f} mm/us  chi2/dof {r['chi2'] / r['dof']:.2f}")
        assert dp < 0.05 and dw < 0.5e-3, f"{mode} round-trip failed"

    print("\nALL PASS")
    return ok


if __name__ == '__main__':
    main()
