#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
analyze.py -- reduce HV-monitor currents to charge per beam pulse, per sub-run.

    .venv/bin/python ntof_july_analysis/flash_charge/analyze.py --src <mirror>

`<mirror>` is a directory holding, for each run of interest:

    <mirror>/run_NN/run_config.json
    <mirror>/run_NN/<subrun>/hv_monitor.csv
    <mirror>/beam_intensity/beam_intensity_<date>.csv

Fetch it with `fetch.sh` (July runs live on EOS, August runs on the DAQ).  Only
the reduced products land in the repo:

    results/flash_charge_subruns.csv   one row per (run, sub-run, detector)
    results/flash_charge_summary.md    the null tests and the headline numbers

Everything downstream -- including the MPGD2026 figures -- reads the CSV, so
re-running this after more beam refreshes the talk.
"""
from __future__ import annotations

import argparse
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import charge_lib as C  # noqa: E402

# Runs worth reducing, and what each one is for.
RUNS = {
    'run_19':  'resist scan, Ar/iso 95/5, the run_19 recovery baseline',
    'run_42':  'resist scan, Ar/iso 90/10',
    'run_57':  'resist scan 580->520 V at 2 V steps, flash_random; SAME sub-runs '
               'as the run_57 recovery map -- the join that makes charge vs dead time',
    'run_58':  'singles 2-D drift x resist scan',
    'run_61':  'doubles drift x resist scan',
    'run_64':  'drift x resist scan',
    'run_67':  'drift x resist x plastic-threshold scan (the operating-point run)',
    'run_79':  'production point, the run the preliminary tracks come from',
    'run_157': 'BEAM-OFF cosmic reference at the production point (null test)',
    'run_158': 'production statistics run (beam-on reference)',
    'run_159': 'BEAM-OFF cosmic reference, zero beam pulses (hard null test)',
}

BEAM_OFF = ('run_157', 'run_159')


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True, help='local mirror of hv_monitor.csv trees')
    ap.add_argument('--out', default=os.path.join(HERE, 'results'))
    ap.add_argument('--runs', default='', help='comma list, default all present')
    args = ap.parse_args()

    pulses = C.PulseLog(os.path.join(args.src, 'beam_intensity'))
    want = args.runs.split(',') if args.runs else list(RUNS)

    rows: list[C.SubrunCharge] = []
    for run in want:
        d = os.path.join(args.src, run)
        if not os.path.isdir(d):
            print(f'  .. {run}: not in mirror, skipped')
            continue
        r = C.run_charges(d, pulses)
        rows.extend(r)
        print(f'  {run}: {len(r)} (sub-run x det) rows')

    os.makedirs(args.out, exist_ok=True)
    csv_path = os.path.join(args.out, 'flash_charge_subruns.csv')
    C.write_csv(rows, csv_path)
    print(f'\nwrote {csv_path}  ({len(rows)} rows)')

    _summary(rows, os.path.join(args.out, 'flash_charge_summary.md'))
    return 0


def _summary(rows: list[C.SubrunCharge], path: str) -> None:
    L: list[str] = []
    w = L.append
    w('# Charge per beam pulse from the resistive-layer supply current')
    w('')
    w('Generated by `ntof_july_analysis/flash_charge/analyze.py`. '
      'Method and caveats: `charge_lib.py` docstring and '
      '`HANDOFF_FLASH_CHARGE_2026-08-09.md`.')
    w('')

    w('## Null test -- beam-off runs')
    w('')
    w('The estimator is mean minus median of the supply current. With no beam '
      'it must return zero, and it does:')
    w('')
    w('| run | det | resist V | leakage [uA] | dI [uA] | pulse rate [Hz] |')
    w('|---|---|---:|---:|---:|---:|')
    for run in BEAM_OFF:
        for det in 'ABCD':
            s = [r for r in rows if r.run == run and r.det == det]
            if not s:
                continue
            di = float(np.mean([r.di_ua for r in s]))
            w(f'| {run} | {det} | {s[0].resist_v:.0f} | {s[0].i_median_ua:.3f} | '
              f'{di:+.4f} | {s[0].pulse_rate_hz:.3f} |')
    w('')

    w('## Rate scaling -- the estimator tracks the beam, not the detector')
    w('')
    w('run_157 and run_158 sit at the *identical* HV setpoint hours apart, with '
      'a ~10x different beam-pulse rate. Charge per pulse has to be the same; '
      'the current does not.')
    w('')
    w('| run | det | rate [Hz] | dI [uA] | Q/pulse [nC] |')
    w('|---|---|---:|---:|---:|')
    for run in ('run_157', 'run_158'):
        for det in ('A', 'C'):
            s = [r for r in rows if r.run == run and r.det == det]
            if not s:
                continue
            w(f'| {run} | {det} | {s[0].pulse_rate_hz:.3f} | '
              f'{np.mean([r.di_ua for r in s]):.4f} | '
              f'{np.mean([r.q_per_pulse_nc for r in s]):.1f} |')
    w('')

    w('## Production operating point (run_158)')
    w('')
    w('| det | resist V | leakage [uA] | Q/pulse [nC] | per channel [pC] | '
      'x CSA full scale (600 fC / 50 fC) | trust |')
    w('|---|---:|---:|---:|---:|---:|---|')
    for det in 'ABCD':
        s = [r for r in rows if r.run == 'run_158' and r.det == det]
        if not s:
            continue
        q = float(np.mean([r.q_per_pulse_nc for r in s]))
        e = float(np.sqrt(np.sum([r.q_err_nc ** 2 for r in s])) / len(s))
        pc = q * 1e3 / C.CHANNELS_PER_DET
        w(f'| {det} | {s[0].resist_v:.0f} | {s[0].i_median_ua:.3f} | {q:.0f} +- {e:.0f} | '
          f'{pc:.0f} | {C.csa_full_scale_multiple(pc, 600):.0f} / '
          f'{C.csa_full_scale_multiple(pc, 50):.0f} | '
          f'{"clean" if s[0].leak_ok else "LEAKY -- see caveats"} |')
    w('')

    w('## Charge vs resist HV (run_57, the scan the recovery map was measured on)')
    w('')
    for det in 'ABCD':
        v, q, dq, n = C.by_hv([r for r in rows if r.run == 'run_57'], det,
                              clean_only=False)
        if v.size == 0:
            continue
        lo, hi = q[0], q[-1]
        w(f'- **det {det}**: {lo:.0f} nC at {v[0]:.0f} V -> {hi:.0f} nC at '
          f'{v[-1]:.0f} V, a factor **{hi / lo:.1f}** over {v[-1] - v[0]:.0f} V '
          f'({v.size} points)')
    w('')
    w('That rise is the gas gain curve, measured through the charge it delivers '
      'rather than through the signal it makes -- which is the point, since the '
      'signal is what saturates.')
    w('')

    with open(path, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print(f'wrote {path}')


if __name__ == '__main__':
    raise SystemExit(main())
