#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
calibration.py -- the one place the DREAM<->n_TOF time calibration is read from.

Anything that maps a DREAM trigger time into the n_TOF time base should get its
constants here rather than hard-coding them. Several modules in this package
still carry the pre-2026-07-30 numbers inline (K = 1.089e-4, T0 = -197.5 ns,
bands +-150 ns plus a [250,450] ns satellite); those numbers were fitted on the
OFFICIAL processing of run 224572 and are wrong for anything we analyse. They
are left in place only so that the figures they produced stay reproducible --
see the banner in each.

The authority is `DREAM_NTOF_CALIBRATION.md`. The machine-readable export lives
in the DAQ repo, `nTof_x17_DAQ/calibrations/dream_ntof/`, and is regenerated by
`match_study/scripts/export_daq_calib.py`.

NOTHING HERE TRANSFERS BETWEEN RUN PAIRS. `load()` takes the pair it was fitted
on and will refuse a different one unless you say `strict=False`, because a
silent mismatch here is a 1.35 % rate error -- 45 ns at 3 ms, 1 us at 80 ms --
which no window catches and nothing else flags.

USAGE
    from ntof_dream_merge.calibration import load
    cal = load()                       # the run_79 <-> 224572/v12 calibration
    t_pred = cal.predict(t_dream, arm) # + per-bunch term, if you have one
    ok = abs(t_cand - t_pred) < cal.window_ns
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

_HERE = Path(__file__).resolve().parent
CALIB_DIR = _HERE.parents[1] / 'nTof_x17_DAQ' / 'calibrations' / 'dream_ntof'
STUDY_DATA = _HERE / 'match_study' / 'data'

FITTED_ON = dict(dream_run='run_79', ntof_run=224572,
                 ntof_processing='v12_liqpileup')
ARMS = ('A', 'B', 'C', 'D')


@dataclass
class TimeMap:
    K: float
    T0_ns: float
    arm_offset_ns: dict
    window_ns: float
    fitted_on: dict = field(default_factory=lambda: dict(FITTED_ON))
    source: str = ''

    @property
    def bands(self):
        """The accept window as a list of (lo, hi), for code that wants bands.

        ONE band. The [250,450] ns satellite of the old calibration was a
        delayed wall lobe of the OLD pulse reconstruction; on a reprocessed file
        it carries no signal and only background.
        """
        return [(-self.window_ns, self.window_ns)]

    def predict(self, t_dream, arm=None, dk=0.0, da=0.0):
        """Where in the n_TOF time base a DREAM trigger at `t_dream` should be.

        `arm` is 'A'..'D' (or an array of them); `dk`, `da` are that bunch's
        per-bunch clock terms, which are ALWAYS re-fitted and are zero here.
        """
        a = 0.0 if arm is None else self.arm_offset_ns[arm]
        return t_dream * (1.0 + self.K + dk) + self.T0_ns + a + da

    def check(self, dream_run=None, ntof_run=None, ntof_processing=None):
        """Raise unless the pair asked for is the pair this was fitted on."""
        want = dict(dream_run=dream_run, ntof_run=ntof_run,
                    ntof_processing=ntof_processing)
        bad = {k: (v, self.fitted_on.get(k)) for k, v in want.items()
               if v is not None and v != self.fitted_on.get(k)}
        if bad:
            raise ValueError(
                'this calibration was fitted on '
                f'{self.fitted_on} and does not describe {bad}. K, T0 and the '
                'per-arm offsets do NOT transfer -- re-fit with '
                'match_study/scripts/fit_timebase.py. Pass strict=False only if '
                'you know why.')


def _from_export(path: Path) -> TimeMap:
    d = json.loads(path.read_text())
    p = d['provenance']
    return TimeMap(K=float(d['K']), T0_ns=float(d['T0_ns']),
                   arm_offset_ns={a: float(d['arm_offset_ns'][a]) for a in ARMS},
                   window_ns=float(d['window_ns']),
                   fitted_on=dict(dream_run=p['dream_run'],
                                  ntof_run=p['ntof_run'],
                                  ntof_processing=p['ntof_processing']),
                   source=str(path))


def _from_study(path: Path) -> TimeMap:
    import numpy as np
    tb = json.loads(path.read_text())
    return TimeMap(
        K=float(tb['fitted']['K']), T0_ns=float(tb['fitted']['T0']),
        arm_offset_ns={a: float(np.mean([v['a'] for v in tb['per_arm'][a].values()]))
                       for a in ARMS},
        window_ns=25.0, source=str(path))


def load(dream_run=None, ntof_run=None, ntof_processing=None,
         strict=True) -> TimeMap:
    """The calibration, from the DAQ export if present, else the study output."""
    export = sorted(CALIB_DIR.glob('time_map_*.json')) if CALIB_DIR.is_dir() else []
    if export:
        cal = _from_export(export[-1])
    elif (STUDY_DATA / 'timebase.json').exists():
        cal = _from_study(STUDY_DATA / 'timebase.json')
    else:
        raise FileNotFoundError(
            f'no calibration found in {CALIB_DIR} or {STUDY_DATA}. Run '
            'match_study/scripts/fit_timebase.py, then export_daq_calib.py.')
    if strict:
        cal.check(dream_run, ntof_run, ntof_processing)
    return cal


if __name__ == '__main__':
    c = load()
    print(f'source        {c.source}')
    print(f'fitted on     {c.fitted_on}')
    print(f'K             {c.K:.6e}')
    print(f'T0            {c.T0_ns:+.2f} ns')
    print(f'arm offsets   ' + '  '.join(f'{a} {c.arm_offset_ns[a]:+6.2f}'
                                        for a in ARMS))
    print(f'accept        |r| < {c.window_ns:.0f} ns   bands {c.bands}')
